---
abstract: 'A storage class for Catalyst Authentication using DBIx::Class'
author:
  - 'Jason Kuri (jayk@cpan.org)'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Authentication-Store-DBIx-Class
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Model::DBIC::Schema: 0.18
  Catalyst::Plugin::Authentication: 0.10008
  Catalyst::Runtime: 0
  DBIx::Class: 0
  perl: 5.8.1
version: 0.108
